name: Say hello
on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hey contactcovid"
      - name: Get current date
        run: date
      - run: ls -la