name: Deployment pipeline
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout current repository    
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: x64
      - name: Update pip
        run: pip install --no-cache --upgrade pip
      - name: Install Rasa
        run: pip install rasa
      - name: Train server
        run: rasa train
      - name: Start server
        run: rasa run --enable-api --cors \"*\"
      - name: Start actions server
        run: rasa run actions